import datetime

def write_to_file(fname, s):
    f = open(fname, 'w')
    f.write(s)
    f.close()

def create_post(company, rating):
    body = '''Based on current public sentiment towards {}, we have issued {} a {} rating.
<br>
<br>
*This post was automatically generated by Augury.*
    '''.format(company, company, 'sell' if rating == 0 else 'buy')

    s = '''---
layout: post
time: {}
rating: {}
---

{}'''.format(datetime.datetime.now().strftime('%I:%M %p'), 'sell' if rating == 0 else 'buy', body)

    post_name = '-'.join((company + (' Sell' if rating == 0 else ' Buy')).split(' '))

    write_to_file('web/_posts/{}-{}.md'.format(datetime.datetime.now().strftime('%Y-%m-%d'), post_name), s)


if __name__ == '__main__':
    create_post('General Motors', 0)
    create_post('Apple', 2)
    create_post('Facebook', 2)
